<?php

namespace Silnin\ShareTell\StoryBundle\Repository;

use DateTime;
use Silnin\ShareTell\StoryBundle\Entity\Contribution;
use Silnin\ShareTell\StoryBundle\Entity\Story;
use Silnin\UserBundle\Entity\User;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends \Doctrine\ORM\EntityRepository
{
    public function createContribution(Story $story, User $user, $content)
    {
        $contribution = new Contribution();

        $contribution->setContent($content);
        $contribution->setAuthor($user);
        $contribution->setStory($story);
        $contribution->setStatus('published');
        $contribution->setCreated(new DateTime());

        $this->getEntityManager()->persist($contribution);
        $this->getEntityManager()->flush();

        return $contribution;
    }

    public function getContributionsForStory($story)
    {
        return $this->getEntityManager()->getRepository('SilninShareTellStoryBundle:Contribution')->findBy(
            [
                'story' => $story
            ]
        );
    }
}
