<?php

namespace Silnin\ShareTell\StoryBundle\Repository;
use DateTime;
use Silnin\ShareTell\StoryBundle\Entity\Participant;
use Silnin\ShareTell\StoryBundle\Entity\Story;
use Silnin\UserBundle\Entity\User;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function createParticipant(User $user, Story $story)
    {
        $participant = new Participant();
        $participant->setJoined(new DateTime());
        $participant->setStatus('active');
        $participant->setStory($story);
        $participant->setUser($user);

        $this->getEntityManager()->persist($participant);
        $this->getEntityManager()->flush();

        return $participant;
    }

    public function getParticipantsForStory(Story $story)
    {
        return $this->getEntityManager()->getRepository('SilninShareTellStoryBundle:Participant')->findBy(
            [
                'story' => $story
            ]
        );
    }

    public function getParticipantsForUser(User $user)
    {
        return $this->getEntityManager()->getRepository('SilninShareTellStoryBundle:Participant')->findBy(
            [
                'user' => $user
            ]
        );
    }
}
