silnin_o_auth_auth_login:
    path: /oauth/v2/auth_login
    defaults: { _controller: SilninOAuthBundle:Security:login }

silnin_o_auth_auth_login_check:
    path: /oauth/v2/auth_login_check
    defaults: { _controller: SilninOAuthBundle:Security:loginCheck }