story:
    resource: "@StoryBundle/Resources/config/routing.yml"
    prefix:   /

browser:
    resource: "@BrowserBundle/Resources/config/routing.yml"
    prefix:   /browse

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

frontpage:
    resource: "@FrontpageBundle/Resources/config/routing.yml"
    prefix:   /
