silnin_share_tell_story:
    resource: "@SilninShareTellStoryBundle/Resources/config/routing.yml"
    prefix:   /story

silnin_share_tell_dashboard:
    resource: "@SilninShareTellDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

silnin_share_tell_frontpage:
    resource: "@SilninShareTellFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"