# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

acme_oauth_server_security:
    resource: "@SilninOAuthBundle/Resources/config/routing.yml"
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

silnin_share_tell_dashboard:
    resource: "@SilninShareTellDashboardBundle/Resources/config/routing.yml"

silnin_share_tell_frontpage:
    resource: "@SilninShareTellFrontpageBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

silnin_share_tell_story:
    resource: "@SilninShareTellStoryBundle/Resources/config/routing.yml"
    prefix:   /api