#security:
#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username
#
#    firewalls:
#        api:
#            pattern: ^/api                             # All URLs are protected
#            fos_oauth: true                            # OAuth2 protected resource
#            stateless: true                            # Do no set session cookies
#            anonymous: false                           # Anonymous access is not allowed
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
#                always_use_default_target_path: false
#                default_target_path:            /dashboard
#            anonymous: true                            # Anonymous access is not allowed
#            logout:       true
#        oauth_token:                                   # Everyone can access the access token URL.
#            pattern: ^/oauth/v2/token
#            security: false
#
#    access_control:
#        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/dashboard, role: ROLE_USER }
#        - { path: ^/story, role: ROLE_USER }
#        - { path: ^/api, role: ROLE_USER }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/read, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }



security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
        oauth_login:
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
                use_referer: true
            anonymous: true
        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
                use_referer: true
            anonymous: false
            logout: true
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

    access_control:
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth, role: IS_AUTHENTICATED_FULLY }
#    firewalls:
#        api:
#            pattern: ^/api
#            fos_oauth: true
#            stateless: true
#        oauth_authorize:
#            pattern: ^/oauth/v2/auth
#            form_login:
#                provider: fos_userbundle
#                check_path: /oauth/v2/auth_login_check
#                login_path: /oauth/v2/auth_login
#            anonymous: true
#        oauth_token:
#            pattern: ^/oauth/v2/token
#            security: false
#        controlpanel:
#            pattern: ^/dashboard
#            fos_oauth: true
#            security: true
#            stateless: true
#            logout: true
#        frontpage:
#            pattern: ^/
#            anonymous: true
#
#    access_control:
#        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/dashboard, role: ROLE_USER }