<?php

namespace Silnin\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\UserManagerInterface;
use Silnin\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @var UserManagerInterface
     */
    private $userManager;

    /**
     * @param UserManagerInterface $userManager
     */
    public function setUserManager(UserManagerInterface $userManager)
    {
        $this->userManager = $userManager;
    }

    /**
     * @param string $email
     */
    public function deleteUserByEmail($email)
    {
        /** @var User $user */
        $user = $this->getEntityManager()->getRepository('SilninUserBundle:User')->findOneBy(
            [
                'email' => $email
            ]
        );

        if (is_null($user)) {
            return;
        }

        $this->getEntityManager()->remove($user);
        $this->getEntityManager()->flush();
    }

    /**
     * @param string $email
     * @return User|null
     */
    public function getByEmail($email)
    {
        return $this->getEntityManager()->getRepository('SilninUserBundle:User')->findOneBy(
            [
                'email' => $email
            ]
        );

    }

    /**
     * @param $email
     * @param $username
     * @param $password
     * @return User
     */
    public function createUser($email, $username, $password)
    {
        $user = $this->userManager->createUser();
        $user->setEmail($email);
        $user->setUsername($username);
        $user->setPassword($password);

        $this->userManager->updateUser($user);

        return $user;
    }
}
