<?php

namespace Silnin\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Silnin\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $email
     */
    public function deleteUserByEmail($email)
    {
        /** @var User $user */
        $user = $this->getEntityManager()->getRepository('SilninUserBundle:User')->findOneBy(
            [
                'email' => $email
            ]
        );

        if (is_null($user)) {
            return;
        }

        $this->getEntityManager()->remove($user);
        $this->getEntityManager()->flush();
    }

    /**
     * @param string $email
     * @return User|null
     */
    public function getByEmail($email)
    {
        return $this->getEntityManager()->getRepository('SilninUserBundle:User')->findOneBy(
            [
                'email' => $email
            ]
        );

    }
}
