silnin_share_tell_story_join:
    path:   /join/{reference}
    defaults: { _controller: silnin_share_tell_story.default_controller:joinAction }

silnin_share_tell_story_contribute:
    path:   /{reference}/contribute
    defaults: { _controller: silnin_share_tell_story.default_controller:contributeAction }

silnin_share_tell_story_new:
    path:   /new
    defaults: { _controller: silnin_share_tell_story.default_controller:newAction }

silnin_share_tell_story_create_confirmation:
    path:   /confirmation
    defaults: { _controller: silnin_share_tell_story.default_controller:createConfirmAction }

silnin_share_tell_story_play:
    path:   /{reference}
    defaults: { _controller: silnin_share_tell_story.default_controller:playAction }

#silnin_share_tell_story_homepage:
#    path:     /
#    defaults: { _controller: SilninShareTellStoryBundle:Default:index }
