services:

  silnin.story_repository:
    class: Silnin\ShareTell\StoryBundle\Repository\StoryRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
        - Silnin\ShareTell\StoryBundle\Entity\Story

  silnin.participant_repository:
    class: Silnin\ShareTell\StoryBundle\Repository\ParticipantRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
        - Silnin\ShareTell\StoryBundle\Entity\Participant
